{{- if or (.Values.windowsEnforcer.allWinNodes.enable) (.Values.windowsEnforcer.WinLinuxNodes.enable) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-windows-enforcer-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-windows-ds
    khulnasoft.component: windows-enforcer
{{ include "khulnasoft.labels" . | indent 4 }}
data:
  {{- if .Values.multiple_gateway.enabled }}
  KHULNASOFT_SERVER: {{ join "," .Values.multi_gates }}
  {{- else }}
  KHULNASOFT_SERVER: {{ .Values.global.gateway.address | default "khulnasoft-gateway-svc" }}:{{ .Values.global.gateway.port | default "8443" }}
  {{- end }}
  KHULNASOFT_ENFORCER_TYPE: "full"
{{- end }}
