{{ $relName := .Release.Name }}
{{ $relNamespace := .Release.Namespace }}
{{- range $i, $cert := .Values.additionalCerts }}
{{- if $cert.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.secretName }}
  namespace: {{ $relNamespace }}
  labels:
    app: {{ $relName }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" $ | indent 4 }}
data:
  cert.pem: {{ $cert.certFile | b64enc | quote }}
{{- end }}
{{- end }}
