---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scanner-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scanner
    khulnasoft.component: scanner
{{ include "khulnasoft.labels" . | indent 4 }}
data:
  SCALOCK_LOG_LEVEL: {{ .Values.logLevel | default "INFO" }}
  {{- if .Values.enableLivenessProbe }}
  KHULNASOFT_HEALTH_MONITOR_ENABLED: "true"
  KHULNASOFT_HEALTH_MONITOR_PORT: {{ .Values.livenessProbe.httpGet.port | quote }}
  {{- end }}
  {{- if .Values.cyberCenter.mtls.enabled }}
  KHULNASOFT_PRIVATE_KEY: "/opt/khulnasoft/ssl/key.pem"
  KHULNASOFT_PUBLIC_KEY: "/opt/khulnasoft/ssl/cert.pem"
  KHULNASOFT_ROOT_CA: "/opt/khulnasoft/ssl/ca.pem"
  {{- if .Values.cyberCenter.mtls.rootCA_fileName }}
  OFFLINE_CC_MTLS_ENABLE: "1"
  {{- end }}
  {{- end }}
