---
{{- if .Values.tunnel.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.tunnel.appName }}
  labels:
    app.kubernetes.io/name: {{ .Values.tunnel.appName }}
    app.kubernetes.io/instance: {{ .Values.tunnel.appName }}
    app.kubernetes.io/version: {{ .Values.tunnel.image.tag | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.tunnel.appName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tunnel.appName }}
    namespace: {{ .Release.Namespace }}
{{- end }}