---
{{- if .Values.tunnel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tunnel.appName }}-tunnel-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.tunnel.appName }}
    app.kubernetes.io/instance: {{ .Values.tunnel.appName }}
    app.kubernetes.io/version: {{ .Values.tunnel.image.tag | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- end }}